# Generated by Django 3.1.5 on 2021-01-23 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pecs', '0002_image_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
