# Generated by Django 3.1.5 on 2021-02-18 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pecs', '0005_auto_20210216_1525'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['description']},
        ),
    ]
